[project]
name = 'protocol'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.kratos-governance-token-trait]
path = 'contracts/kratos-governance-token-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc]
path = 'contracts/sbtc.clar'
clarity_version = 2
epoch = 2.4

[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = 2.4

[contracts.swap]
path = 'contracts/swap/swap.clar'
clarity_version = 2
epoch = 2.4

[contracts.swap-trait]
path = 'contracts/swap/swap-trait.clar'
clarity_version = 2
epoch = 2.4

[contracts.swap-x-y-z]
path = 'contracts/swap/swap-x-y-z.clar'
clarity_version = 2
epoch = 2.4

[contracts.token-gkrt]
path = 'contracts/token-gkrt.clar'
clarity_version = 2
epoch = 2.4

[contracts.token-klpt]
path = 'contracts/token-klpt.clar'
clarity_version = 2
epoch = 2.4

[repl]
clarity_wasm_mode = false
show_timings = false

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
